### ISSUE TITLE
Copyleft in audio/video libraries

### ISSUE THREAD

**Issue by azam** [azam/azam.github.io#2]
These are some thoughts when trying to implement a MPEG-DASH streaming backend on Rust.
  
I found out that a lot of media related libraries such as the almighty [`FFmpeg`](https://ffmpeg.org/), are GPL or LGPL. This sort of sets the landscape for other media-related projects to be GPL, since it eases linking to `FFmpeg` without delegating to spawning an external process to intereface with it, and also asking users to install `FFmpeg` separately.
  
However if you have to link to `FFmpeg` for whatever reason, there is an option to link it as LGPL (basically it is about building `FFmpeg` minus its GPL dependencies) and keep your current license. As it goes for most copyleft projects, there are other non-technical requirements like provisioning a way to distribute `FFmpeg` source etc. They have a good checklist on how to comply on their legal page ([here](https://ffmpeg.org/legal.html)).
  
Meanwhile, I would like to keep my projects on the more open MIT/BSD licenses, and also viably sustainable to use by me and also implementors, so naturally I want to avoid dependencies with copyleft licenses. The good thing is that I do not need an all-in-one library, so that makes it a little easier to find for existing implementations. Smaller scoped, single purpose libraries tends to have a more open license. Excellent libraries such as [`mp4-rust`](https://github.com/alfg/mp4-rust), and [`rust-id3`](https://github.com/polyfloyd/rust-id3) exists in non-copyleft licenses. I hope there is a trend for these single purpose libraries to keep being non-copyleft licenses.
  
On a sidenote, I use [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) with the following `deny.toml` file and add `cargo deny check license` on CI to make sure that I don't accidentally infect myself with copyleft dependencies.

```toml
[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "both"
# We want to deny GPL-like crates
copyleft = "deny"
default = "deny"
allow = [
    # Approved: used in ring
    "OpenSSL",
    # Approved: used in unicode-ident
    "Unicode-DFS-2016",
]

# See https://github.com/briansmith/ring/blob/main/LICENSE for clarification.
# ring LICENSE file is more on exlpaining all licenses used, but crate itself is mostly ISC-like.
[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
```
